version: '2'

volumes:
  # HLS playlist and video segments store
  video-data: {}

  # Sender application bundle volume
  sender-dist: {}

  # Receiver application bundle volume
  receiver-dist: {}

  # Backend binaries
  streamer-dist: {}

services:

  web:
    build: frontend/server
    volumes:
      # Video content
      - 'video-data:/data/:ro'
      # Sender app
      - 'sender-dist:/sender/dist/:ro'
      # Receiver app
      - 'receiver-dist:/receiver/dist/:ro'
    restart: always

  streamer:
    build: streamer
    volumes:
      # Binaries
      - 'streamer-dist:/streamer:ro'
      # Video content
      - 'video-data:/data/'
    environment:
      DATA_DIRECTORY: '/data/video'
      INDEX_FILE_NAME: 'index.m3u8'
      TWITCH_CLIENT_ID: '${TWITCH_CLIENT_ID}'
      STREAM_INFO_TIMEOUT: 30
      PROXY_TIMEOUT: 60
      TS_SEGMENT_LENGTH: 4
      TS_SEGMENT_COUNT: 4

  irc-relay:
    image: globidocker/twitch-irc
    command: none 'twitch-irc-websocket'
    restart: always
