FROM node

RUN npm install -g bower
RUN npm install -g live-server
RUN npm install -g gulp

WORKDIR /src

CMD ["/bin/bash"]


# docker run -i -t --rm -p 3000:3000 -p 35729:35729 -v `pwd`:/src amanent/nodedev:0.1
